# Generated by Django 5.0.6 on 2024-11-01 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("required_certification", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Responder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization", models.CharField(max_length=100)),
                (
                    "certification_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("certification_expiry", models.DateField()),
                ("is_on_duty", models.BooleanField(default=False)),
                ("last_deployment", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specializations",
                    models.ManyToManyField(to="responders.specialization"),
                ),
            ],
        ),
    ]
