# Generated by Django 5.1.2 on 2024-11-02 08:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
