# Generated by Django 4.2.16 on 2024-12-24 19:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HEALTH", "Health & Safety"),
                            ("MANAGEMENT", "Management & Leadership"),
                            ("COMMUNICATION", "Communication & Public Relations"),
                            ("EDUCATION", "Education & Tutoring"),
                            ("TECH", "Technology & IT Support"),
                            ("LOGISTICS", "Logistics & Transportation"),
                            ("LANGUAGE", "Language Skills"),
                            ("ENVIRONMENT", "Environmental Conservation"),
                            ("ANIMAL_CARE", "Animal Care"),
                            ("MENTORING", "Mentoring & Coaching"),
                            ("ADMIN_SUPPORT", "Administrative Support"),
                            ("ARTS", "Arts & Culture"),
                            ("HUMAN_SERVICES", "Human Services"),
                            ("LEGAL", "Legal Assistance"),
                            ("FUNDRAISING", "Fundraising & Grant Writing"),
                            ("RESEARCH", "Research & Data Analysis"),
                            ("DISASTER_RELIEF", "Disaster Relief"),
                            ("ADVOCACY", "Advocacy & Policy"),
                            ("SPORTS", "Sports & Recreation"),
                            ("HOSPITALITY", "Hospitality & Events"),
                            ("OTHERS", "Other Categories"),
                        ],
                        default="OTHERS",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("name", "category")},
            },
        ),
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("availability", models.JSONField(default=dict)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                            ("EXPERT", "Expert"),
                        ],
                        max_length=20,
                    ),
                ),
                ("max_travel_distance", models.IntegerField(default=10)),
                ("verified_hours", models.IntegerField(default=0)),
                ("rating", models.FloatField(default=0.0)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="VolunteerSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proficiency_level",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="volunteer.skill",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="skill_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="volunteer.volunteer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VolunteerRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="volunteer.volunteer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="volunteer",
            name="skills",
            field=models.ManyToManyField(
                through="volunteer.VolunteerSkill", to="volunteer.skill"
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
