# Generated by Django 4.2.16 on 2024-12-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, null=True)),
                ("size", models.IntegerField(null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("AUDIO", "AUDIO"),
                            ("VIDEO", "VIDEO"),
                            ("IMAGE", "IMAGE"),
                            ("DOCUMENT", "DOCUMENT"),
                            ("OTHERS", "OTHERS"),
                        ],
                        default="IMAGE",
                        max_length=20,
                    ),
                ),
                ("media_url", models.CharField(blank=True, max_length=255, null=True)),
                ("cloud_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CSRResourceMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, null=True)),
                ("size", models.IntegerField(null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("AUDIO", "AUDIO"),
                            ("VIDEO", "VIDEO"),
                            ("IMAGE", "IMAGE"),
                            ("DOCUMENT", "DOCUMENT"),
                            ("OTHERS", "OTHERS"),
                        ],
                        default="IMAGE",
                        max_length=20,
                    ),
                ),
                ("media_url", models.CharField(blank=True, max_length=255, null=True)),
                ("cloud_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventResources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, null=True)),
                ("size", models.IntegerField(null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("AUDIO", "AUDIO"),
                            ("VIDEO", "VIDEO"),
                            ("IMAGE", "IMAGE"),
                            ("DOCUMENT", "DOCUMENT"),
                            ("OTHERS", "OTHERS"),
                        ],
                        default="IMAGE",
                        max_length=20,
                    ),
                ),
                ("media_url", models.CharField(blank=True, max_length=255, null=True)),
                ("cloud_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IncidentMediaResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, null=True)),
                ("size", models.IntegerField(null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("AUDIO", "AUDIO"),
                            ("VIDEO", "VIDEO"),
                            ("IMAGE", "IMAGE"),
                            ("DOCUMENT", "DOCUMENT"),
                            ("OTHERS", "OTHERS"),
                        ],
                        default="IMAGE",
                        max_length=20,
                    ),
                ),
                ("is_sensitive", models.BooleanField(default=False)),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("media_url", models.CharField(blank=True, max_length=255, null=True)),
                ("cloud_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfilePicResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, null=True)),
                ("size", models.IntegerField(null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("AUDIO", "AUDIO"),
                            ("VIDEO", "VIDEO"),
                            ("IMAGE", "IMAGE"),
                            ("DOCUMENT", "DOCUMENT"),
                            ("OTHERS", "OTHERS"),
                        ],
                        default="IMAGE",
                        max_length=20,
                    ),
                ),
                ("media_url", models.CharField(blank=True, max_length=255, null=True)),
                ("cloud_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Resources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, null=True)),
                ("size", models.IntegerField(null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("AUDIO", "AUDIO"),
                            ("VIDEO", "VIDEO"),
                            ("IMAGE", "IMAGE"),
                            ("DOCUMENT", "DOCUMENT"),
                            ("OTHERS", "OTHERS"),
                        ],
                        default="IMAGE",
                        max_length=20,
                    ),
                ),
                ("media_url", models.CharField(blank=True, max_length=255, null=True)),
                ("cloud_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
